### PR TITLE
implement Guard System

### LINKED ISSUE #47: Guard System - Bounty $100
Essentially, implement a guard system. It's laughable one doesn't exist.

https://github.com/TrinityCore/TrinityCore/issues/11563
https://github.com/azerothcore/azerothcore-wotlk/issues/10571

Long term we'll mod this to be more custom but at least getting a blizzlike base is doable.

Note this is also going to require actually placing the guard post game objects as no spawns exist.

Needs better defining exactly how this should work.

### PR DESCRIPTION
**Pull request by sogladev**
**Changes proposed**:
Allow guards to be summoned by creatures (e.g. civilians) using guardpost gameobjects

### terminology:
**a. guard NPC**: defined by flag `CreatureFlagsExtra.CREATURE_FLAG_EXTRA_GUARD`
```
CREATURE_FLAG_EXTRA_GUARD = 0x00008000,   // Creature is guard
```
**b. who can call guards**: civilian **or** creature flag

1.  civilian NPC `CreatureFlagsExtra.CREATURE_FLAG_EXTRA_CIVILIAN`

```
CREATURE_FLAG_EXTRA_CIVILIAN = 0x00000002,   // not aggro (ignore faction/reputation hostility)
```
2. creature with flag `UnitFlags2.UNIT_FLAG2_CALL_GUARDS`
```
UNIT_FLAG2_CALL_GUARDS = 0x00080000,   // Summons a guard if an opposite faction player gets near or attacks.
```

**c. guardpost (guard station) gameobject** : type `GameobjectTypes.GAMEOBJECT_TYPE_GUARDPOST`

```
GAMEOBJECT_TYPE_GUARDPOST              = 21,
```
`Data0`: entry of guard NPC summoned
`Data1`: the amount of guard charges, 1 recharges every 60 seconds

**d. player** 

### how are guards summoned
guards (**a.**) are summoned by "creatures" (**b.**) by 2 triggers:
1. when a player is in aggro range: 
  a. summons 1 guard from a nearby guardpost OR calls a nearby guard to attack
  b. on success, the creature will say text
  c. this effect has a 10-second cooldown
2. when a player engages in combat: 
  a. creature will always say text, summon a guard OR call a guard to attack
  b. this effect has no cooldown
  c. triggered once for every player that engages
  d. 1-3 guards are summoned. This is random but 2-3 occur less frequently, from video source

guard is summoned near the location of the guardpost and moves toward the attacker. If the guard leaves combat it returns to the civilian who summoned it.

A guard is summoned for 5 minutes. If the guard is still in combat, it will stay in combat until OOC and then despawn. The guard will despawn after 10 minutes regardless. 

PvP combat
1. when a player is attacked in PvP
  a. checks if Area allows player to call for guards
  b. alert guards in range (was already implemented)
  c. trigger a guard post object in range

### data
NPCs say texts are taken from Vmangos' implementation

each of the guardposts is placed on or near their `.tele` locations. Minus "Wyvern Guard Post" (161558) with 2 charges for wyvern NPC; There is no gryphon counterpart

### What about summon spells?
Guardposts gameobjects are used to handle this as there's no need for summon spells. These summon spells contain a creature entry, which is also present in the guardpost gameobject in `Data0`. I assume spells were used at some point, but were replaced by guardpost objects.

### Why not StaticFlag?
`CreatureStaticFlags.CREATURE_STATIC_FLAG_CALLS_GUARDS`
It was easier to use extra_flag. Staticflag requires DB structure changes, 2 cherry picks from TC Master to handle static flag properly
1. introduce creature_template_difficulty
https://github.com/TrinityCore/TrinityCore/commit/06d0b16f158e8793860d9edd11b990f20b1d0dac#diff-0b60c19367c864b8168981a49bbe74ce2a32e867eed8302805b0b09c497145f6L79
3. add static flags to db
https://github.com/TrinityCore/TrinityCore/commit/7282a1772568111f95a1fb85e95f92421439c097

### sources
vmangos' implementation, this uses no guard objects
https://github.com/vmangos/core/commit/5d7467f79b58eaa46c17f4a9fb2a395d3d3ec00a#diff-e34d7edcd38a875f86b19557712df345b411038995345a5f52aa7c8e6648bfd8

a. multiple guards 2 if attacked https://youtu.be/DMoXuDyZ_eY?si=uk30r0a93gIulr5l&t=45 . AC mentions 1-3 guards
b. mage left side screen fireballs a civilian. guards don't spawn at the attacked NPC, likely at at the "guard station" object https://youtu.be/DMoXuDyZ_eY?si=yVM1VJy7OTUvY7s6&t=47
c. no cooldown on yell. Every time new unit engages, yells and tries to summon a guard. But only if triggered by engage https://youtu.be/LEmiZsv78Bo?si=WIgcNpNEKPDhpldd&t=115
d. no multiple yells if triggered by moving close. Triggered again ~5 seconds later
https://youtu.be/r7aveH_fyTw?si=VSiJjy44jvH_dHqC&t=22

**Target branch(es)**: 335/6x

**Issues addressed**: Fixes #47

**Tests performed**: (Does it build, tested in-game, etc)

tested with 1-2 horde characters, mostly around goldshire

**Known issues and TODO list**:

- [ ]  TBC/Wrath models/areas are missing their say text + call guard flags
- [ ] Guardposts spawns are not sniffed
- [ ]

### CODE REVIEW

**Comment by sogladev** [comment]
PR needs adjustment with new info from https://github.com/Project-Epoch/TrinityCore/issues/47#issuecomment-2418140296

**Comment by kaytotes** [comment]
@sogladev Just confirming this is ready for testing? :)

**Comment by sogladev** [comment]
> @sogladev Just confirming this is ready for testing? :)

Yes, this can be tested

**Comment by kaytotes** [comment]
Prioing testing this tomorrow.

**Pull request merged**
